var zipCode;
var airportCode;
var cityName;

var longitude;
var latitude;

var currentTemperature;
var currentIcon;
var currentCondition;
var windSpeed;
var gusts;
var feelsLike;
var visibility;
var humidity;
var dewPoint;
var pressure;
var pressureTrend;
var forecastNarrative = [];
var forecastTemp = [];
var forecastIcon = [];
var forecastPrecip = [];
var outlookHigh = [];
var outlookLow = [];
var outlookCondition = [];
var outlookIcon = [];
var radarImage;
var zoomedRadarImage;
var alertsActive;
var alerts = [];
